---
name: Planet Technomancy
link: http://planet.technomancy.us
owner_name: Phil Hagelberg
owner_email: technomancy@gmail.com
template_files: planet/index.html.erb
output_directory: public/planet
cache_directory: /tmp/planet/cache
feeds:
  Tim Malabuyo: http://feeds.feedburner.com/IntelligentDesign/
  Doug Alcorn: http://www.lathi.net/xml/rss20/feed.xml
  programming musings: http://jaortega.wordpress.com/feed/
  Mark Pilgrim: http://diveintomark.org/feed/
  Hackety Hack: http://feeds.feedburner.com/HacketyOrg
  John Resig: http://ejohn.org/index.rdf
  Evan Henshaw-Plath: http://anarchogeek.com/feed/atom.xml
  chris2: http://chneukirchen.org/blog/index.atom
  Andre Arko: http://arko.net/feed/atom.xml
  Dr Nic Williams: http://feeds.feedburner.com/DrNic
  Martin Fowler: http://martinfowler.com/bliki/bliki.atom
  Wondermark: http://www.wondermark.com/wondermarkrss.xml
  xkcd: http://xkcd.com/rss.xml
  Penny Arcade: http://www.penny-arcade.com/rss.xml
  Dinosaur Comics: http://rsspect.com/rss/qwantz.xml
  Achewood: http://achewood.com/rss.php
  Forrest Chang: http://funkworks.blogspot.com/atom.xml
  Alex Vollmer: http://blog.livollmers.net/index.php/feed/atom
  Jim Weirich: http://onestepback.org/index.cgi/index.rss
  Kevin Clark: http://feeds.feedburner.com/Gluttonous
  JD Huntington: http://blog.jdhuntington.com/atom.xml
  Giles Bowkett: http://feeds.feedburner.com/gilesbowkett
  PJ Hyett: http://feeds.feedburner.com/pjhyett
  Dave Thomas: http://pragdave.blogs.pragprog.com/pragdave/atom.xml
  Evan Phoenix: http://blog.fallingsnow.net/feed/
  Coda Hale: http://feeds.feedburner.com/codablog
  Amy Hoy: http://feeds.feedburner.com/slash7/rss
  Alex Payne: http://feeds.feedburner.com/al3x
  Chad Fowler: http://feeds.feedburner.com/Chadfowlercom
  Steve Yegge: http://steve-yegge.blogspot.com/atom.xml
  minor emacs wizardry: http://emacs.wordpress.com/feed/
  Rick Olson: http://feeds.feedburner.com/TechnoWeenie
  Ryan Daigle: http://feeds.feedburner.com/RyansScraps
  Dave Astels: http://blog.daveastels.com/feed
  Erik Kastner: http://metaatem.net/feed/atom
  David Goodlad: http://david.goodlad.ca/feed/atom.xml
  Phil Hagelberg: http://technomancy.us/feed/atom.xml
  Github: http://feeds.feedburner.com/github
  Rails Podcast: http://feeds.feedburner.com/rubyonrails_transcript
  Wilson Bilkovich: http://metaclass.org/feed/atom.xml
  Ryan Davis: http://blog.zenspider.com/atom.xml
  Ezra Z: http://brainspl.at/xml/rss20/feed.xml
  Adam Keys: http://therealadam.com/feed/
  Hyperstruct: http://feeds.feedburner.com/hyperstruct
  Courtenay Gasking: http://blog.caboo.se/feed/atom.xml
  Seth Falcon: http://userprimary.net/user/feed/
  Hampton Catlin: http://hamptoncatlin.com/feed/atom.xml
  Dave Bourgeois: http://lessonsfrombabel.blogspot.com/atom.xml
  Garry Dolley: http://feeds.feedburner.com/scientist-home
  Mauricio Fernandez: http://eigenclass.org/hiki.rb?c=rss;format=1;tags=blog
  Jason Wong: http://jasonwong.org/feed/atom.xml
  Sam Ruby: http://www.intertwingly.net/blog/index.atom
  Err the Blogp: http://feeds.feedburner.com/errtheblog
  epistemologic: http://epistemologic.com/feed/
  Eric Hodel: http://feeds.feedburner.com/segment7/VjcA
  Oliver Steele: http://feeds.feedburner.com/osteele
  Planet Zacchaeus: http://planet.philisha.net/rss.xml
  Josh Susser: http://feeds.feedburner.com/hasmanythrough
  Tom Preston-Werner: http://feeds.feedburner.com/ruby_is_awesome
  James Clark: http://blog.jclark.com/feeds/posts/default